version: '2'
services:
  database:
    container_name: locationapp-database
    image: postgres:9.5.2
    ports:
     - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
